version: '3.9'

services:
  apache:
    build: ./server
    restart: always
    volumes:
      - ./server:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'app_db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: '123456'
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  adminer_mqsql:
    image: adminer
    restart: always
    ports:
      - 8081:8080

